Repository zachjamesgreen/black_thursday, pull requests merged in 2021-04, with the labels that each got.

#4 Create find merchant by id method
  lib/merchant.rb
  lib/merchant_repository.rb
  spec/merchant_repository_spec.rb
Labels: enhancement

#7 Update repository
  .gitignore
  lib/item.rb
  lib/item_repository.rb
  lib/merchant.rb
  lib/merchant_repository.rb
  lib/repository.rb
  spec/item_repository_spec.rb
  spec/item_spec.rb
  spec/merchant_repository_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#8 Fix spec harness issues
  lib/item.rb
  lib/item_repository.rb
  lib/merchant.rb
  lib/merchant_repository.rb
  lib/sales_analyst.rb
  lib/sales_engine.rb
  spec/item_repository_spec.rb
  spec/item_spec.rb
  spec/merchant_repository_spec.rb
  spec/sales_engine_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#9 Create invoice spec class
  lib/invoice.rb
  lib/invoice_repository.rb
  lib/sales_engine.rb
  spec/invoice_repository_spec.rb
  spec/invoice_spec.rb
  spec/item_repository_spec.rb
  spec/merchant_repository_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#11 Create transact repo
  lib/transaction.rb
  lib/transaction_repository.rb
  spec/transaction_repository_spec.rb
  spec/transaction_spec.rb
Labels: enhancement

#12 Create transact repo
  lib/sales_engine.rb
  spec/spec_helper.rb
Labels: documentation

#13 Create customer files
  lib/customer.rb
  lib/customer_repository.rb
  lib/sales_engine.rb
  spec/customer_repository_spec.rb
  spec/customer_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#14 Invoice item repo
  lib/invoice_item.rb
  lib/invoice_item_repository.rb
  lib/invoice_repository.rb
  lib/sales_engine.rb
  spec/invoice_item_repository_spec.rb
  spec/invoice_item_spec.rb
  spec/invoice_repository_spec.rb
  spec/item_repository_spec.rb
  spec/merchant_repository_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#15 Refactor specs and sales engine files
  lib/sales_engine.rb
  spec/customer_repository_spec.rb
  spec/invoice_item_repository_spec.rb
  spec/invoice_repository_spec.rb
  spec/item_repository_spec.rb
  spec/merchant_repository_spec.rb
  spec/transaction_repository_spec.rb
Labels: bug

#18 Sales analyst
  Gemfile
  Gemfile.lock
  README.md
  Rakefile
  data/invoice_items.csv
  iteration_pattern.md
  lib/customer_repository.rb
  lib/invoice.rb
  lib/invoice_item.rb
  lib/invoice_item_repository.rb
  lib/invoice_repository.rb
  lib/item.rb
  lib/item_repository.rb
  lib/merchant.rb
  lib/merchant_repository.rb
  lib/repository.rb
  lib/sales_analyst.rb
  lib/sales_engine.rb
  lib/transaction.rb
  lib/transaction_repository.rb
  runner.rb
  spec/customer_repository_spec.rb
  spec/customer_spec.rb
  spec/factories.rb
  spec/invoice_item_repository_spec.rb
  spec/invoice_item_spec.rb
  spec/invoice_repository_spec.rb
  spec/invoice_spec.rb
  spec/item_repository_spec.rb
  spec/item_spec.rb
  spec/merchant_repository_spec.rb
  spec/merchant_spec.rb
  spec/sales_analyst_spec.rb
  spec/sales_engine_spec.rb
  spec/spec_helper.rb
  spec/transaction_repository_spec.rb
  spec/transaction_spec.rb
Labels: bug, enhancement
